messages {
        # Message displayed when you try to start a trivia and there is already an active one
        start-trivia-already-active="&fA trivia question is currently active!"
        # Message displayed when you try to stop a trivia and there is not an active one
        stop-trivia-not-active="&fOh no! There isn't an active trivia question!"
        # Message displayed when aa trivia is timed up and no one answered
        times-up-trivia="&fTimes up!"
        # Message displayed when the trivia is ended and should not how the answer
        trivia-not-show-answer="&fBetter luck next time!"
        # Message displayed when the trivia has been completed and tell who get it
        player-answer-good="&d %player% &f got it! "
        # Message displayed when the answer should be displayed and there is only one answer
        one-answer-display="The answer was : "
        # Message displayed when the answer should be displayed and there are several answers
        several-answers-display="The answers were : "
}